"""empty message

Revision ID: 990a0355ff66
Revises: 83be4cc9eb04
Create Date: 2023-06-09 09:03:12.703862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990a0355ff66'
down_revision = '83be4cc9eb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
 
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
